public class DataTypeExample {
  
    public static void showDataTypes(){
         
        Integer employeeCount = 100;
        Decimal annualRevenue = 5000.75;
        String accountName = 'Test Example';
        Boolean isActive = true;
        Date todayDate = Date.today();
        
       System.debug(employeeCount);
       System.debug(annualRevenue);
       System.debug(accountName);
       System.debug(isActive);
       System.debug(todayDate);
           
            }

}